  MXWeather:
    container_image: MXWeather
    image: ubuntu:MXWeather
    restart: ${RESTARTMODE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/MXWeather/data:/opt/CumulusMX/data
      - ${ROOT}/MXWeather/backup:/opt/CumulusMX/backup
      - ${ROOT}/MXWeather/log:/var/log/nginx
      - ${ROOT}/MXWeather/MXdiags:/opt/CumulusMX/MXdiags
      - ${ROOT}/MXWeather/config:/opt/CumulusMX/config
      - ${ROOT}/MXWeather/publicweb:/opt/CumulusMX/publicweb
      - ${ROOT}/MXWeather/templates:/opt/CumulusMX/web
#     - /tmp/Easyweather.dat:/opt/CumulusMX/Easyweather.dat           # Required to allow for no USB device, and allows for injecting custom EasyWeather data
#     - /tmp/Easyweatherplus.dat:/opt/CumulusMX/Easyweatherplus.dat   # Required to allow for no USB device, and allows for injecting custom EasyWeather data
    ports:
      - 8998:8998
      - 80:80
